version: '3'
services:

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: vietstem-db
      POSTGRES_USER: vietstem
      POSTGRES_PASSWORD: S8mPhM5QYz2NMG3v

  app:
    build: .
    image: vfastdevelope/vietstem:0.1
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/home/node/app
